<a href="https://colab.research.google.com/github/INFINITY-RUBER/Curso_Deep_Learning_Con_TernsorFlow_Machine-Learning_e_IA-/blob/master/scripts/tema03/02-multiple-operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip install tensorflow==1.14

# Operaciones por capas

In [0]:
import tensorflow as tf
session = tf.Session()

- $X \in \mathbb R_{3\times 4}$

In [8]:
import numpy as np
my_array = np.array([[1.,3.,5.,7.],
                     [-2.,0.,7.,6.],
                     [-6.,-1.,0.,3.]])
my_array # matrix (3 x 4)

array([[ 1.,  3.,  5.,  7.],
       [-2.,  0.,  7.,  6.],
       [-6., -1.,  0.,  3.]])

In [9]:
x_vals = np.array([my_array, my_array+1])
x_vals # matrix (3 x 4)

array([[[ 1.,  3.,  5.,  7.],
        [-2.,  0.,  7.,  6.],
        [-6., -1.,  0.,  3.]],

       [[ 2.,  4.,  6.,  8.],
        [-1.,  1.,  8.,  7.],
        [-5.,  0.,  1.,  4.]]])

In [0]:
x_data = tf.placeholder(tf.float32, shape=(3,4))# placeholder de 3 filas y 4 columnas , None como dimencion significa que es variable la dimension

- $m_1 \in \mathbb R^4$
- $m_2, a_1\in \mathbb R$

In [0]:
m1 = tf.constant([[1.], [0.], [-2.],[5.]])# vector columna (4 x 1)
m2 = tf.constant([[7.]])#  (1 x 1)
a1 = tf.constant([[15.]])# (1 x 1)

$$[(X\cdot m_1)\cdot m_2]+a_1$$

In [0]:
prod1 = tf.matmul(x_data, m1)
prod2 = tf.matmul(prod1, m2)
add1 = tf.add(prod2, a1)

In [13]:
for x_val in x_vals:
    print(session.run(add1, feed_dict={x_data: x_val}))

[[197.]
 [113.]
 [ 78.]]
[[225.]
 [141.]
 [106.]]
