<a href="https://colab.research.google.com/github/INFINITY-RUBER/Curso_Deep_Learning_Con_TernsorFlow_Machine-Learning_e_IA-/blob/master/scripts/tema01/04-matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Cómo trabajar con matrices

In [0]:
!pip install tensorflow==1.14

In [2]:
tf.__version__

'1.14.0'

In [0]:
import tensorflow as tf
session = tf.Session()

### 1. Cómo crear matrices

In [4]:
identity = tf.diag([1.,1.,1.,1.])
print(session.run(identity)) # crea una matris identidad

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
A = tf.truncated_normal([3,4])
print(session.run(A))

[[-0.2301007  -0.63401127 -1.048298   -1.1452522 ]
 [ 0.6471514   0.59793466 -0.17379223  0.80798   ]
 [ 1.4560295  -0.63798004  0.11949411  1.2146362 ]]


In [6]:
B = tf.fill([3,4], 1988.)
print(session.run(B))

[[1988. 1988. 1988. 1988.]
 [1988. 1988. 1988. 1988.]
 [1988. 1988. 1988. 1988.]]


In [9]:
C = tf.random_uniform([4,3])# crea una matriz uniforme de 4 filas x 3 columnas
print(session.run(C))

[[0.40494168 0.06496    0.10092688]
 [0.75844204 0.20864618 0.6499796 ]
 [0.3874582  0.1954751  0.9668968 ]
 [0.32903135 0.6690961  0.9750556 ]]


In [11]:
# crear matris apartir de un objeto de datos
import numpy as np
data = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]])
D = tf.convert_to_tensor(data)
print(session.run(D))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## 2. Operar con matrices

In [12]:
print(session.run(A+B))

[[1989.4833 1987.0654 1988.8431 1986.6024]
 [1987.388  1987.1847 1986.8528 1987.5602]
 [1988.3042 1986.6919 1986.666  1989.407 ]]


In [13]:
print(session.run(B-B))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
print(session.run(tf.matmul(A,C)))# multiplicar matris donde A[4X3] y C[3X4] 

[[ 0.5881008   0.24439725  0.3943368 ]
 [-1.7099488  -0.6786355  -0.57544327]
 [-0.44714046 -0.50996083  0.96941733]]


In [15]:
print(session.run(tf.matmul(A, identity)))

[[-1.6636072  -0.5542362   1.3789642  -0.24767213]
 [-0.01934127  0.49384278  0.45621446  0.05464964]
 [-0.02768271  1.0313135   0.7829085  -1.139209  ]]


# 3. Tranpuesta, determinante, inversa

In [16]:
# Tranpuesta
print(session.run(tf.transpose(D)))

[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


In [19]:
#Tranpuesta
print(session.run(tf.transpose(A)))

[[ 1.7893519   0.09932958 -1.7455466 ]
 [-0.9771057   0.70915806  0.51312894]
 [-0.02004225 -1.3351558   0.21852647]
 [-1.0193074  -0.9379225  -0.09104424]]


In [21]:
# determinante
print(session.run(tf.matrix_determinant(D)))

6.66133814775094e-16


In [24]:
E = tf.convert_to_tensor(np.array([[1.,2.,3.], [-3., -6., -1], [0., 5, -3]]))
print(session.run(E))

[[ 1.  2.  3.]
 [-3. -6. -1.]
 [ 0.  5. -3.]]


In [26]:
# determinante E
print(session.run(tf.matrix_determinant(E)))

-40.0


In [30]:
# inversa
print(session.run(tf.matrix_inverse(E)))

[[-0.575 -0.525 -0.4  ]
 [ 0.225  0.075  0.2  ]
 [ 0.375  0.125  0.   ]]


In [33]:
print(session.run(tf.matmul(E,(session.run(tf.matrix_inverse(E))))))   # multiplicar matris donde A[4X3] y C[3X4] 

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.22044605e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  5.55111512e-17  1.00000000e+00]]


## 4. Descomposición

In [34]:
print(session.run(tf.cholesky(identity)))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## 5. Valores y vectores propios

In [35]:
print(session.run(tf.self_adjoint_eigvals(E)))

[-10.24888536  -0.66882335   2.91770871]


In [36]:
# Matrix de descomposicion de los vectores
print(session.run(tf.self_adjoint_eig(E)))

(array([-10.24888536,  -0.66882335,   2.91770871]), array([[ 0.21442787,  0.60489799, -0.76688924],
       [ 0.80402486,  0.3364893 ,  0.49022339],
       [-0.55458517,  0.72171557,  0.41420034]]))
