<a href="https://colab.research.google.com/github/INFINITY-RUBER/Curso_Deep_Learning_Con_TernsorFlow_Machine-Learning_e_IA-/blob/master/scripts/tema07/04-multilayer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install tensorflow==1.14


     |████████████████████████████████| 109.2MB 96kB/s 
     |████████████████████████████████| 491kB 35.5MB/s 
     |████████████████████████████████| 3.2MB 43.7MB/s 
  Found existing installation: tensorflow-estimator 2.2.0
    Uninstalling tensorflow-estimator-2.2.0:
      Successfully uninstalled tensorflow-estimator-2.2.0
  Found existing installation: tensorboard 2.2.2
    Uninstalling tensorboard-2.2.2:
      Successfully uninstalled tensorboard-2.2.2
  Found existing installation: tensorflow 2.2.0
    Uninstalling tensorflow-2.2.0:
      Successfully uninstalled tensorflow-2.2.0


# Redes neuronales multicapas

### Ejemplo 1D 

In [0]:
import tensorflow as tf
import numpy as np
session = tf.Session()

In [0]:
data_size = 25
data_1d = np.random.normal(size = data_size)
x_input_1d = tf.placeholder(shape=[data_size], dtype=tf.float32)

In [0]:
# CAPA DE CONVOLUCION
def conv_layer_1d(input_1d, my_filter): # Expando las dimenciones
    input_2d = tf.expand_dims(input_1d, 0)
    input_3d = tf.expand_dims(input_2d, 0)
    input_4d = tf.expand_dims(input_3d, 3)
    convolution = tf.nn.conv2d(input_4d, filter = my_filter, strides = [1,1,1,1], padding="VALID")
    output = tf.squeeze(convolution)# para aplanar el resultado
    return(output)

In [0]:
my_filter = tf.Variable(tf.random_normal(shape=[1,5,1,1]))
my_conv_output = conv_layer_1d(x_input_1d, my_filter)

In [0]:
def activation(input_1d):
    return tf.nn.relu(input_1d)
my_activation_output = activation(my_conv_output)

In [0]:
# CAPA DE MAX POOL
def max_pool(input_1d, width): # Expando las dimenciones
    input_2d = tf.expand_dims(input_1d, 0)
    input_3d = tf.expand_dims(input_2d, 0)
    input_4d = tf.expand_dims(input_3d, 3)
    pooling = tf.nn.max_pool(input_4d, ksize=[1,1,width,1], strides=[1,1,1,1], padding="VALID")
    output = tf.squeeze(pooling) # para aplanar el resultado
    return(output)

In [0]:
my_maxpool_ouput = max_pool(my_activation_output, width=5)

In [0]:
#CAPA DE FULLY CONECTED
def fully_connected(input_layer, num_output):
    weight_shape = tf.squeeze(tf.stack([tf.shape(input_layer), [num_output]]))
    weight = tf.random_normal(weight_shape, stddev=0.1)
    bias = tf.random_normal(shape=[num_output])
    input_layer_2d = tf.expand_dims(input_layer,0)
    full_output = tf.add(tf.matmul(input_layer_2d, weight), bias)
    full_output_1d = tf.squeeze(full_output)
    return(full_output_1d)

In [0]:
my_full_output = fully_connected(my_maxpool_ouput, 5)

In [0]:
init = tf.global_variables_initializer()
session.run(init)

In [0]:
feed_dict = {x_input_1d: data_1d}

In [17]:
data_1d

array([-1.61726888, -1.2193498 ,  0.14061903, -0.51001781, -2.3379341 ,
       -0.25664928,  0.85916285,  0.52469564, -0.95995039,  0.93116705,
        1.88122448,  1.07597929, -0.40668817, -0.13557741,  0.10961391,
       -0.05065995, -0.19606411,  0.97491762, -0.66798195,  0.30129464,
       -1.45373693, -0.26006064,  0.45680252, -1.24921309,  0.09392702])

In [18]:
session.run(my_filter)

array([[[[ 1.3166825 ]],

        [[ 0.55290055]],

        [[ 0.5848349 ]],

        [[-1.5671657 ]],

        [[ 0.4578321 ]]]], dtype=float32)

In [20]:
# Operación de convolución
print("Input: tamaño 25, Operación: convolución con filtro de tamaño 5 + stride de tamaño 1, Resultado: tamaño 21")
print(session.run(my_conv_output, feed_dict=feed_dict))

Input: tamaño 25, Operación: convolución con filtro de tamaño 5 + stride de tamaño 1, Resultado: tamaño 21
[-2.9924686   1.7204036  -0.66857964 -3.220502   -3.9795308   2.3746858
  0.26192856 -1.7508934  -1.521334    3.4707274   3.0966964   0.9175976
 -0.5567058   0.60607904 -1.8320295   1.5798395  -1.2475268   3.2497196
 -0.94643307 -1.8469701   0.20998342]


In [21]:
# Función de activación
print("Input: tamaño 21, Operación: ReLU al array anterior, Resultado: tamaño 21")
print(session.run(my_activation_output, feed_dict=feed_dict))

Input: tamaño 21, Operación: ReLU al array anterior, Resultado: tamaño 21
[0.         1.7204036  0.         0.         0.         2.3746858
 0.26192856 0.         0.         3.4707274  3.0966964  0.9175976
 0.         0.60607904 0.         1.5798395  0.         3.2497196
 0.         0.         0.20998342]


In [24]:
# Operción de Max Pooling
print("Input: tamaño 21, Operación: maxpooling con ventana de tamaño 5 + stride de tamaño 1, Resultado: tamaño 17")
print(session.run(my_maxpool_ouput, feed_dict=feed_dict))

Input: tamaño 21, Operación: maxpooling con ventana de tamaño 5 + stride de tamaño 1, Resultado: tamaño 17
[1.7204036 2.3746858 2.3746858 2.3746858 2.3746858 3.4707274 3.4707274
 3.4707274 3.4707274 3.4707274 3.0966964 1.5798395 1.5798395 3.2497196
 3.2497196 3.2497196 3.2497196]


In [25]:
# Capa Totalmente Conectada
print("Input: tamaño 17, Operación de conectar totalmente la entrada con 5 valores de salida, Resultado: tamaño 5")
print(session.run(my_full_output, feed_dict=feed_dict))

Input: tamaño 17, Operación de conectar totalmente la entrada con 5 valores de salida, Resultado: tamaño 5
[-0.24400637 -0.00846422 -0.59755856 -2.2791066   1.1354127 ]


### Ejemplo 2D

In [0]:
session = tf.Session()

In [0]:
data_size = [10,10] # Defino las variables  matrix de 10x10 
data_2d = np.random.normal(size = data_size)
x_input_2d = tf.placeholder(dtype=tf.float32, shape=data_size)

In [0]:
# Operacion de convolucion
def conv_layer_2d(input_2d, my_filter):
    input_3d = tf.expand_dims(input_2d, 0)
    input_4d = tf.expand_dims(input_3d, 3)
    convolution = tf.nn.conv2d(input_4d, filter=my_filter, strides = [1,2,2,1], padding="VALID")
    output = tf.squeeze(convolution)
    return(output)

In [0]:
my_filter = tf.Variable(tf.random_normal(shape=[2,2,1,1]))
my_conv_output = conv_layer_2d(x_input_2d, my_filter)

In [0]:
# funcion de activacion
def activation(input_2d):
    return(tf.nn.relu(input_2d))

In [0]:
my_activation_output = activation(my_conv_output)

In [0]:
def max_pool(input_2d, width, height):
    input_3d = tf.expand_dims(input_2d, 0)
    input_4d = tf.expand_dims(input_3d, 3)
    pooling = tf.nn.max_pool(input_4d, ksize=[1,height,width,1], strides=[1,1,1,1], padding="VALID")
    output = tf.squeeze(pooling)
    return(output)

In [0]:
my_maxpool_ouput = max_pool(my_activation_output, width=2, height=2)

In [0]:
def fully_connected(input_layer, num_output):
    flat_input = tf.reshape(input_layer, [-1])
    weight_shape = tf.squeeze(tf.stack([tf.shape(flat_input), [num_output]]))
    weight = tf.random_normal(weight_shape, stddev=0.1)
    bias = tf.random_normal(shape=[num_output])
    input_layer_2d = tf.expand_dims(flat_input,0)
    full_output = tf.add(tf.matmul(input_layer_2d, weight), bias)
    full_output_1d = tf.squeeze(full_output)
    return(full_output_1d)

In [0]:
my_full_output = fully_connected(my_maxpool_ouput, 5)

In [0]:
init = tf.global_variables_initializer()
session.run(init)

In [0]:
feed_dict = {x_input_2d: data_2d}

In [40]:
data_2d

array([[-1.57786905, -0.8925134 , -1.82861835,  1.47669137,  1.29035429,
         0.70158705, -1.30698668, -0.03468009, -0.34565806, -0.55014821],
       [-0.34750069,  2.23079769,  0.48136414,  1.61382821, -0.88852339,
         0.59607236, -2.33019196, -1.37138319,  0.79335721,  0.31710252],
       [ 1.28482351, -0.03413729,  0.26152285,  0.69857255,  0.4504426 ,
        -0.96112054, -1.06962072, -0.86364201,  0.02486261, -1.43372643],
       [ 0.25403643,  0.28984598,  0.75975712, -0.42827294, -1.41419828,
        -0.56150306, -0.76056631,  0.84573065,  2.07105045, -0.60685941],
       [ 1.13062963, -1.10488586, -0.84163777, -1.56806842, -1.24429712,
         0.1907664 ,  2.41512398, -0.68046141, -1.91013148, -0.20283875],
       [ 0.55163484, -0.19099095,  0.66930829,  1.14551258,  1.13943175,
        -0.36397595,  1.43199114, -1.96945234, -0.18184546,  1.38318944],
       [ 0.0674058 ,  0.94275723,  0.51578169, -1.45809749, -0.10406067,
         0.36799364, -0.43464492, -0.31212797

In [41]:
session.run(my_filter)

array([[[[-0.13213387]],

        [[-1.085194  ]]],


       [[[-2.8135052 ]],

        [[-1.2922696 ]]]], dtype=float32)

In [42]:
# Operación de convolución
print("Input: tamaño 10x10, Operación: convolución con filtro de tamaño 2x2 + stride de tamaño 2x2, Resultado: tamaño 5x5")
print(session.run(my_conv_output, feed_dict=feed_dict))

Input: tamaño 10x10, Operación: convolución con filtro de tamaño 2x2 + stride de tamaño 2x2, Resultado: tamaño 5x5
[[-0.728057   -4.800696    0.7977214   8.538535   -1.9992058 ]
 [-1.2220151  -2.376779    5.687951    2.1254976  -3.4900992 ]
 [-0.25559473 -1.5505462  -2.7780468  -1.0645378  -0.8033181 ]
 [-3.5823784   4.5656576   2.4520388  -5.2333245   2.5697112 ]
 [-2.670629   -2.8735926   4.899216    4.1959705   6.024027  ]]


In [46]:
# Función de activación (los negativos se hacen ceros)
print("Input: tamaño 5x5, Operación: ReLU al array anterior, Resultado: tamaño 5x5")
print(session.run(my_activation_output, feed_dict=feed_dict))

Input: tamaño 5x5, Operación: ReLU al array anterior, Resultado: tamaño 5x5
[[0.        0.        0.7977214 8.538535  0.       ]
 [0.        0.        5.687951  2.1254976 0.       ]
 [0.        0.        0.        0.        0.       ]
 [0.        4.5656576 2.4520388 0.        2.5697112]
 [0.        0.        4.899216  4.1959705 6.024027 ]]


In [47]:
# Operción de Max Pooling 
print("Input: tamaño 5x5, Operación: maxpooling con ventana de tamaño 2x2 + stride de tamaño 1, Resultado: tamaño 4x4")
print(session.run(my_maxpool_ouput, feed_dict=feed_dict))

Input: tamaño 5x5, Operación: maxpooling con ventana de tamaño 2x2 + stride de tamaño 1, Resultado: tamaño 4x4
[[0.        5.687951  8.538535  8.538535 ]
 [0.        5.687951  5.687951  2.1254976]
 [4.5656576 4.5656576 2.4520388 2.5697112]
 [4.5656576 4.899216  4.899216  6.024027 ]]


In [48]:
# Capa Totalmente Conectada
print("Input: tamaño 4x4, Operación de conectar totalmente la entrada con 5 valores de salida, Resultado: tamaño 5")
print(session.run(my_full_output, feed_dict=feed_dict))

Input: tamaño 4x4, Operación de conectar totalmente la entrada con 5 valores de salida, Resultado: tamaño 5
[ 1.0922222 -0.6171654 -3.525567  -2.264947   1.0860363]
